name: Test

on:
  pull_request:
    types: [labeled]

jobs:
  test_pull_request:
    if: |
      contains(github.event.pull_request.labels.*.name, 'Please_Review') &&
      !contains(github.event.pull_request.labels.*.name, 'DO_NOT_INTEGRATE')
    runs-on: [self-hosted]
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name: test backend
      run: |
        npm ci
        npm run test
    - name: test frontend
      working-directory: ./front
      run: |
        yarn
        yarn test
