name: Test

on:
  pull_request

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name: test backend
      run: |
        npm ci
        npm run test
    - name: test frontend
      working-directory: ./front
      run: |
        npm ci
        npm run test
