name: "Test"
on:
  pull-request:
    type: [labeled]
    branches:
      - '!master'

jobs:
  build:
    if: ${{ github.event.label.name != 'DO_NOT_INTEGRATE' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!